#region Header
// **    Copyright (C) 2023 Nicolas Reinhard, @LTMX. All rights reserved.
// **    Github Profile: https://github.com/LTMX
// **    Repository : https://github.com/LTMX/Unity.mathx
#endregion

using NUnit.Framework;
using static Unity.Mathematics.math;
using static Unity.Mathematics.mathx;

namespace Unity.Mathematics.Tests
{
	/// Golden values generated by package/.ci/scripts/golden_noise.py (webgl-noise simplex port).
	[TestFixture]
	public class GoldenNoiseTests
	{
		const float Epsilon = 1e-5f;

		[TestCase(0f, 0f, 0f)]
		[TestCase(1.3f, 2.7f, -0.694539405f)]
		[TestCase(0.5f, 0.5f, -0.471332954f)]
		[TestCase(1f, 2f, 0.368337775f)]
		[TestCase(12.34f, 56.78f, -0.563978797f)]
		public void Simplex2_MatchesGolden(float x, float y, float expected)
		{
			var value = new float2(x, y).simplex2();
			Assert.AreEqual(expected, value, Epsilon);
			Assert.IsFalse(float.IsNaN(value));
		}

		[Test]
		public void Fbm2_ThreeOctaves_MatchesGolden() =>
			Assert.AreEqual(0.558005685f, fbm2(new float2(1f, 2f), 3), Epsilon);

		[Test]
		public void Perlin2_IsFiniteAtSamplePoint()
		{
			var value = new float2(1.3f, 2.7f).perlin2();
			Assert.IsFalse(float.IsNaN(value));
			Assert.IsFalse(float.IsInfinity(value));
		}

		[Test]
		public void Worley2_IsNonNegative() =>
			Assert.GreaterOrEqual(worley2(new float2(0.5f, 0.5f)), 0f);

		[Test]
		public void Voronoi2_IsFinite() =>
			Assert.IsFalse(float.IsNaN(voronoi2(new float2(0.5f, 0.5f))));

		[Test]
		public void Simplex2_IsDeterministic()
		{
			var pos = new float2(3.14f, 2.71f);
			Assert.AreEqual(pos.simplex2(), pos.simplex2(), Epsilon);
		}
	}
}
