name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish Zip
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # - name: Build
      # run: cargo build --release
    - name: Upload Zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mything
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
        
