name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
   create-release:
    name: Publish Zip
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3
    - name: Upload Zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/mything
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
        
