name: Create Release

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Extract tag name
        id: extract_tag
        shell: bash
        run: echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"
        
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag }}
          release_name: Release ${{ steps.extract_tag.outputs.tag }}
          draft: false
          prerelease: false
